import type { Metadata } from "next";
import {Montserrat} from 'next/font/google'
import "@/app/styles/globals.css";
import AuthProvider from "@/components/AuthProvider";
import { Session } from "next-auth";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const fontFamily = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <AuthProvider>
    <html lang="en">
      <body
        className={`absolute h-[100vh] w-full antialiased ${fontFamily.className} text-gray-900`}
      >
        {children}
      </body>
    </html>
    </AuthProvider>

  );
}
