import type { Metadata } from "next";
import {Poppins, Montserrat, Playfair} from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const playfair = Playfair({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`absolute h-[100vh] w-full antialiased ${montserrat.className} text-gray-900`}
      >
        {children}
      </body>
    </html>
  );
}
